### PR TITLE
Homework

### PR DESCRIPTION
**Pull request by hkaanturgut**
please check out my first try , thanks

### CODE REVIEW

**Review by ahmetaslan13 — APPROVED** [review]
Great job Hasan!

**Comment by MuratCo** [comment]
amazing, good job

**Review by rataly — COMMENTED** [review]
Can I use your Assignment to show in the class to show VS Code GitHub Pull request plugin and how to accept PR.

**Comment by elevate-cloud** [comment]
LGTM

**Comment by hkaanturgut** [comment]
> Can I use your Assignment to show in the class to show VS Code GitHub Pull request plugin and how to accept PR.

Of course.

**Review by rataly — APPROVED** [review]
I am wondering that can you be able to merge this branch to main :)

**Comment by rataly** [comment]
I am wondering that can you be able to merge this branch to main :)

**Pull request merged**
